// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/main.js', ['blogger'], ['blogger.Storage', 'goog.dom', 'goog.dom.classes', 'goog.style'], false);
goog.addDependency('../../../../src/storage.js', ['blogger.Storage'], [], false);
