// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/rfc.js', ['rfc'], ['goog.dom', 'goog.dom.classes', 'goog.style', 'rfc.Storage'], false);
goog.addDependency('../../../../src/storage.js', ['rfc.Storage'], [], false);
